site_name: InsperSec


nav:
    - Sobre: index.md
    - Sobre Cybersecurity: 
        - Introdução: sobre-cybersecurity.md
        - Princípios Basicos: principios-basicos.md
    - Curso Introdutorio: video-aulas.md



theme: windmill-dark

markdown_extensions:
    - toc:
        permalink: '#'

extra:
  version: 1.0.0